sudo: required
dist: trusty

language: rust
rust:
  - nightly
  - stable
os:
  - linux
cache:
  cargo: true
  apt: true

branches:
  only:
    - master
addons:
  apt:
    packages:
      - libblkid-dev
      - libattr1-dev
      - zfsutils-linux
    sources:
      - sourceline: ppa:zfs-native/stable

script:
  - |
    cargo build &&
    cargo test
